x-app-defaults: &app-defaults
  restart: unless-stopped
  image: listmonk/listmonk:latest
  networks:
    - default
    - traefik
  environment:
    - TZ=Europe/Berlin
  env_file: .env

x-db-defaults: &db-defaults
  image: postgres:16
  ports:
    - "9432:5432"
  networks:
    - default
  restart: unless-stopped
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U listmonk"]
    interval: 10s
    timeout: 5s
    retries: 6
  env_file: .env

services:
  db:
    <<: *db-defaults
    container_name: listmonk-db
    volumes:
      - "${VOLUMES_DIR}/postgres/db/16/data:/var/lib/postgresql/data"

  app:
    <<: *app-defaults
    container_name: listmonk
    depends_on:
      - db
    volumes:
      - ./config.toml:/listmonk/config.toml
      - "${VOLUMES_DIR}/media:/media"
    labels:
      - 'traefik.enable=true'
      - traefik.http.routers.listmonk.middlewares=secheader@file
    command: [sh, -c, "./listmonk --install --idempotent --yes && ./listmonk --upgrade --yes && ./listmonk"]

networks:
  traefik:
    name: traefik
    external: true
