# NOTE: This docker-compose.yml is meant to be just an example guideline
# on how you can achieve the same. It is not intented to run out of the box
# and you must edit the below configurations to suit your needs.

version: "3.7"

x-app-defaults: &app-defaults
  restart: unless-stopped
  image: listmonk/listmonk:latest
  networks:
    - default
    - traefik
  environment:
    - TZ=Europe/Berlin

x-db-defaults: &db-defaults
  image: postgres:16
  ports:
    - "9432:5432"
  networks:
    - default
  restart: unless-stopped
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U listmonk"]
    interval: 10s
    timeout: 5s
    retries: 6

services:
  db:
    <<: *db-defaults
    container_name: listmonk_db
    volumes:
      - type: volume
        source: /srv/listmonk/postgres/db/16
        target: /var/lib/postgresql/data

  app:
    <<: *app-defaults
    container_name: listmonk_app
    depends_on:
      - db
    volumes:
      - ./config.toml:/listmonk/config.toml
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`listmonk.${DOMAINNAME}`)'
      - 'traefik.http.routers.authelia.entrypoints=websecure'

networks:
  traefik:
    name: traefik
    external: true
