x-app-defaults: &app-defaults
  restart: unless-stopped
  image: listmonk/listmonk:latest
  networks:
    - default
    - traefik
  environment:
    - TZ=Europe/Berlin
  env_file: .env

x-db-defaults: &db-defaults
  image: postgres:16
  ports:
    - "9432:5432"
  networks:
    - default
  restart: unless-stopped
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U listmonk"]
    interval: 10s
    timeout: 5s
    retries: 6
  env_file: .env

services:
  db:
    <<: *db-defaults
    container_name: listmonk_db
    volumes:
      - /srv/listmonk/postgres/db/16/data:/var/lib/postgresql/data

  app:
    <<: *app-defaults
    container_name: listmonk_app
    depends_on:
      - db
    volumes:
      - ./config.toml:/listmonk/config.toml
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.listmonk.rule=Host(`listmonk.${DOMAINNAME}`)'
      - 'traefik.http.routers.listmonk.entrypoints=websecure'

networks:
  traefik:
    name: traefik
    external: true
